emarket/config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/create'
  get 'password_resets/edit'
  get 'password_resets/update'
  root 'home#index'

  get '/auth/google_oauth2', to: 'auth#google', as: :google_auth
  get '/auth/google_oauth2/callback', to: 'auth#callback'
  get '/auth/failure', to: 'auth#failure'

  get 'profilo/seguiti', to: 'acquirentes#seguiti', as: :acquirente_seguiti
  get 'follows/create'
  get 'follows/destroy'
  get 'feedbacks/new'
  get 'feedbacks/create'
  get 'return_requests/index'
  get 'return_requests/new'
  get 'return_requests/create'
  get 'return_requests/show'
  get 'return_requests/update'

  get 'ordini_negozi/index'
  get 'ordini_negozi/show'
  get 'ordini_negozi/update'

  get 'gestione_feedback/show'
  get 'gestione_account', to: 'gestione_account#manage'
  get 'statistiche', to: 'statistiche#show'
  get 'signup', to: 'acquirentes#new', as: 'signup'
  get 'admin_signup', to: 'amministratores#new', as: 'admin_signup'

  get 'amministratore/statistiche', to: 'amministratores#statistiche', as: :statistiche_amministratore

  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy', as: 'logout'

  get 'lista_desideri', to: 'lista_desideri#index'
  post 'add_to_wishlist/:id', to: 'lista_desideri#add', as: 'add_to_wishlist'
  delete 'remove_from_wishlist/:id', to: 'lista_desideri#remove', as: 'remove_from_wishlist'

  get 'archivio ordini', to: 'archivio_ordini#index', as: 'archivio_ordini'
  get 'cronologiaricerche', to: 'cronologia_ricerche#index', as: 'cronologia_ricerche'
  delete 'cronologia_ricerche', to: 'cronologia_ricerche#destroy', as: :cancella_cronologia


 
  get "/lingua", to: "lingua#seleziona", as: :lingua
  post "/lingua/cambia", to: "lingua#cambia", as: :cambia_lingua


  get 'admin/feedbacks_segnalati', to: 'amministratores#feedbacks_segnalati', as: 'admin_feedbacks_segnalati'
  delete 'gestione_account/ignora_segnalazione_negozio/:id', to: 'gestione_account#ignora_segnalazione_negozio', as: 'ignora_segnalazione_negozio'



  resources :segnalazioni, only: [:index, :destroy]
  resources :negozios do
    resources :ordini, controller: 'ordini_negozi', only: [:index, :show, :update]
    post 'follow', to: 'follows#create'
    delete 'unfollow', to: 'follows#destroy'
    resources :prodottos, only: [:new, :create]
    member do
      get :statistiche
      get 'recensioni', to: 'recensioninegozio#index'
      get 'feedbacks', to: 'negozios#feedbacks'
      get 'visualizza', to: 'negozios#visualizza'
      get 'seguaci'
      get :segnala_form
      post :segnala
      delete '/segnalazioni/:id/ignora', to: 'segnalazioni#ignora', as: :segnala_ignora
    end
  end


  resources :prodotti do
    resources :statistiche, only: [:index, :show]
  end

  resources :promoziones do
    collection do
      get 'admin'
      get 'negozio'
    end
  end

  resources :categorias, only: [:show]
  resources :prodottos
  resources :recensiones
  resources :variantis
  resources :acquirentes do
    member do
      get 'visualizza'
    end
  end
  
  resources :amministratores, only: [:create, :show, :edit, :update]

  resources :faqs do
    collection do
      get 'admin'
    end
  end

  resources :chat_rooms, only: [:index, :show, :new, :create, :destroy ] do
    post 'messages', to: 'chat_rooms#create_message', as: :messages
    post :start, on: :collection
    post :assistenza, on: :collection
  end

  resource :carrello, only: :show
  resources :carrello_items, only: [:create, :destroy]

  resources :ordini, only: [:new, :create, :show, :index] do
    collection do
      get 'successo', to: 'ordini#successo'
      get 'errore', to: 'ordini#errore'
    end
    post :annulla, on: :member
    post :pagamento, on: :member
    resources :return_requests, only: [:new, :create]
  end

  resources :return_requests, only: [:index, :show, :new, :create, :update]

  resources :negozio_return_requests, only: [:show, :index, :create] do
    member do
      patch :approve
      patch :reject
    end
  end

  resources :gestione_account, only: [:index] do
    member do
      patch :blocca
      patch :sblocca
      delete :elimina
      delete :elimina_negozio
    end
  end

  resources :feedbacks do
    member do
      patch :segnala
      patch :ignora_segnalazione
    end
  end

  resources :password_resets, only: [:new, :create, :edit, :update]

  
  # Monta Action Cable
  mount ActionCable.server => '/cable'
end

emarket/app/models/acquirente.rb
class Acquirente < ApplicationRecord
  # Metodo per la gestione della password
  has_secure_password
  before_create :default_values


  after_initialize :set_default_punti_fedelta

  # Associazioni
  has_many :follows
  has_many :negozi_seguiti, through: :follows, source: :negozio
  has_one :negozio, dependent: :destroy
  has_many :wishlist_items, dependent: :destroy
  has_many :wishlist, through: :wishlist_items, source: :prodotto
  has_many :return_requests, foreign_key: :acquirente_id, dependent: :destroy
  has_many :cronologia_ricercas, dependent: :destroy
  has_many :feedbacks
  has_many :segnalazione_negozios, dependent: :destroy

  
  has_many :messaggi_inviati, as: :mittente, class_name: 'Messaggio', dependent: :destroy
  has_many :messaggi_ricevuti, as: :destinatario, class_name: 'Messaggio', dependent: :destroy
  
  has_one :carrello, dependent: :destroy
  after_create :create_carrello

  has_many :ordini, class_name: "Ordine", dependent: :destroy

  # Validazioni


  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }, on: :create


  validates :id_acquirente, uniqueness: true, allow_nil: true

  # Metodi di utilità
  def nome_completo
    "#{nome} #{cognome}"
  end

  def to_s
    nome_completo
  end

  def create_carrello
    Carrello.create(acquirente: self)
  end

  def default_values
    self.bloccato ||= false
  end

  def create_reset_digest
    token = SecureRandom.urlsafe_base64
    update(
      reset_digest: Digest::SHA256.hexdigest(token),
      reset_sent_at: Time.current
    )
    token
  end

  def reset_token_valid?(token)
    reset_digest.present? &&
      reset_sent_at > 2.hours.ago &&
      Digest::SHA256.hexdigest(token) == reset_digest
  end

  def clear_reset_digest
    update(reset_digest: nil, reset_sent_at: nil)
  end

  def aggiungi_punti_da_ordini(ordini)
    totale = ordini.sum(&:totale)
    punti = (totale / 5).floor
    increment!(:punti, punti)
    punti
  end

  private

  def set_default_punti_fedelta
    self.punti_fedelta ||= 0
  end




end

emarket/app/controllers/acquirentes_controller.rb
class AcquirentesController < ApplicationController
  before_action :set_acquirente, only: %i[ show edit update destroy ]
  before_action :authenticate_acquirente!, only: %i[ show edit update destroy ]
  before_action :authorize_acquirente, only: %i[ show edit update destroy ]

  
  


 def show
    @acquirente = Acquirente.find(params[:id])
    @negozio = @acquirente.negozio
  end


  def new
    @acquirente = Acquirente.new
    @is_new = true
  end

  
  def edit
    @is_new = false
  end


  def create
    @acquirente = Acquirente.new(acquirente_params)
    @is_new = true
    if @acquirente.save
      messaggio = "Acquirente registrato con successo. Per favore, effettuare l\'accesso."
      messaggio_tradotto = TranslationService.translate(messaggio, session[:lingua] || "it")
      redirect_to login_path, notice: messaggio_tradotto

    else
      render :new
    end
  end

  
  def update
    respond_to do |format|
      if @acquirente.update(acquirente_params)
        format.html { redirect_to @acquirente, notice: "Acquirente aggiornato con successo." }
        format.json { render :show, status: :ok, location: @acquirente }
      else
        format.html { render :edit }
        format.json { render json: @acquirente.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def visualizza
    @acquirente = Acquirente.find(params[:id])
  
    if current_user.is_a?(Amministratore) || 
   (current_user.is_a?(Acquirente) && current_user == @acquirente) || 
   !@acquirente.privato
  @profilo_limitato = false
else
  @profilo_limitato = true
end

  end
  

  def seguiti
    @negozi_seguiti = current_user.negozi_seguiti
  end
  
  
  def destroy
    @acquirente.destroy

    respond_to do |format|
      messaggio = "Acquirente was successfully destroyed."
      messaggio_tradotto = TranslationService.translate(messaggio, session[:lingua] || "it")

      format.html { redirect_to login_path, notice: messaggio_tradotto }
      format.json { head :no_content }
    end
  end

  private

    def set_acquirente
      @acquirente = Acquirente.find(params[:id])
    end

  
    def acquirente_params
  
    params.require(:acquirente).permit(:nome, :cognome, :nome_utente, :telefono, :email, :password, :password_confirmation, :indirizzo, :privato)
    end

    def authorize_acquirente
      puts "🔹 Controllo autorizzazione per #{current_user&.id} vs #{@acquirente.id}"
      unless current_user == @acquirente
        messaggio = "Accesso negato: non sei autorizzato ad accedere a questa pagina."
        messaggio_tradotto = TranslationService.translate(messaggio, session[:lingua] || "it")
        redirect_to root_path, alert: messaggio_tradotto and return
      end
    end
end

emarket/app/helpers/acquirentes_helper.rb
module AcquirentesHelper
end

emarket/app/views/acquirentes/_form.html.erb
<%= stylesheet_link_tag 'app', media: 'all' %>

<%= form_with(model: @acquirente, local: true) do |form| %>
  <% if @acquirente.errors.any? %>
  <div class="alert alert-danger border border-danger shadow-sm rounded p-3 mb-4">
    <h4 class="alert-heading"><%= t("errors.messages.missing_fields") %>:</h4>
    <ul class="mb-0">
      <% @acquirente.errors.attribute_names.uniq.each do |attribute| %>
        <li><%= t_google(Acquirente.human_attribute_name(attribute)) %></li>
      <% end %>
    </ul>
  </div>
<% end %>


  <div>
    <%= form.label :nome, t("forms.nome") %>
    <%= form.text_field :nome %>
  </div>

  <div>
    <%= form.label :cognome, t("forms.cognome") %>
    <%= form.text_field :cognome %>
  </div>

  <div>
    <%= form.label :nome_utente, t("forms.nome_utente") %>
    <%= form.text_field :nome_utente %>
  </div>

  <div>
    <%= form.label :telefono, t("forms.telefono") %>
    <%= form.text_field :telefono %>
  </div>

  <div>
    <%= form.check_box :privato %>
    <%= form.label :privato, t("forms.privato") %>
  </div>

  <% if @is_new %>
    <div>
      <%= form.label :email, t("forms.email") %>
      <%= form.email_field :email %>
    </div>
  <% end %>

  <div>
    <%= form.label :password, t("forms.password") %>
    <%= form.password_field :password %>
  </div>

  <div>
    <%= form.label :password_confirmation, t("forms.password_confirmation") %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit t("forms.save") %>
    <%= link_to t("forms.cancel"), root_path, class: "btn" %>
  </div>
<% end %>

emarket/app/views/acquirentes/edit.html.erb
<%= stylesheet_link_tag 'app', media: 'all' %>

<p><%= t_google(notice) %></p>

<h1><%= t('comune.mod_prof') %></h1>

<%= render 'form', acquirente: @acquirente %>

emarket/app/views/acquirentes/new.html.erb
<%= stylesheet_link_tag 'app', media: 'all' %>
<p><%= t_google(notice) %></p>

<h1><%= t('comune.iscriviti') %></h1>

<%= render 'form', acquirente: @acquirente %>

emarket/app/views/acquirentes/seguiti.html.erb
<%= stylesheet_link_tag 'app', media: 'all' %>

<p><%= t_google(notice) %></p>

<h1><%= t('acquirente.negozi_seguiti') %></h1>

<% if @negozi_seguiti.any? %>
  <ul>
    <% @negozi_seguiti.each do |negozio| %>
      <li>
        <%= link_to negozio.nome_negozio, visualizza_negozio_path(negozio) %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p><%= t('acquirente.no_seguiti') %></p>
<% end %>

emarket/app/views/acquirentes/show.html.erb
<%= stylesheet_link_tag 'app', media: 'all' %>

<p><%= t_google(notice) %></p>

<div class="container mt-5">
  <div class="row">
    <div class="col-md-12 mb-4">
      <h1 class="text-center"><%= t('comune.profilo_acquirente') %></h1>
    </div>
  </div>

  <div class="row">
    <!-- Sidebar -->
    <div class="col-md-3">
      <nav class="nav flex-column nav-pills">
        <%= link_to t('acquirente.desideri'), lista_desideri_path, class: 'nav-link btn btn-outline-primary mb-2' %>
        <%= link_to t('acquirente.ordini'), ordini_path, class: 'nav-link btn btn-outline-primary mb-2' %>
        <%= link_to t('acquirente.resi'), return_requests_path, class: 'nav-link btn btn-outline-primary mb-2' %>
        <%= link_to t('acquirente.cronologia'), cronologia_ricerche_path, class: 'nav-link btn btn-outline-primary mb-2' %>
        <% if current_user.negozio.present? %>
        <%= link_to t('comune.tuo_negozio'), negozio_path(current_user.negozio), class: 'nav-link btn btn-outline-primary mb-2' %>
      <% else %>
        <%= link_to t('comune.crea_negozio'), new_negozio_path, class: 'nav-link btn btn-outline-primary mb-2'%>
      <% end %> 
      </nav>
    </div>

    <!-- Main Content -->
    <div class="col-md-9">
      <div class="card mb-4 shadow-sm">
        <div class="card-body">
          <h5 class="card-title"><%= t('comune.dettagli') %></h5>
          <p class="card-text"><strong><%= t('comune.nome') %></strong> <%= @acquirente.nome %> <%= @acquirente.cognome %></p>
          <p class="card-text"><strong><%= t('comune.nome_utente') %></strong> <%= @acquirente.nome_utente %></p>
          <p class="card-text"><strong><%= t('sessions.email') %>: </strong> <%= @acquirente.email %></p>
          <p class="card-text"><strong><%= t('comune.telefono') %></strong> <%= @acquirente.telefono %></p>
          <p class="card-text">
            <%= link_to t('acquirente.seguiti') + " (#{@acquirente.negozi_seguiti.count})", acquirente_seguiti_path, class: "btn btn-outline-primary" %>
          </p>
          <p class="card-text"><strong><%= t('acquirente.punti') %></strong> <%= @acquirente.punti_fedelta %></p>
        </div>
      </div>

      <div class="d-flex justify-content-end">
        <%= link_to t('comune.mod_prof'), edit_acquirente_path(@acquirente), class: 'btn btn-warning me-2' %>
        <%= button_to t('comune.el_prof'), acquirente_path(@acquirente), method: :delete, data: { turbo: false, confirm: t_google("Sei sicuro di voler eliminare il profilo?") }, class: "btn btn-danger" %>
      </div>
    </div>
  </div>
</div>

emarket/app/views/acquirentes/visualizza.html.erb
<%= stylesheet_link_tag 'app', media: 'all' %>
<p><%= t_google(notice) %></p>

<h1><%= t('comune.dettagli') %></h1>

<p><strong><%= t('comune.nome_utente') %></strong> <%= @acquirente.nome_utente %></p>

<% unless @profilo_limitato %>
  <p><strong><%= t('comune.nome') %></strong> <%= @acquirente.nome %></p>
  <p><strong><%= t('comune.cognome') %></strong> <%= @acquirente.cognome %></p>
  <p><strong><%= t('sessions.email') %>: </strong> <%= @acquirente.email %></p>
  <p><strong><%= t('comune.telefono') %></strong> <%= @acquirente.telefono %></p>
<% else %>
  <p><em><%= t('acquirente.privato') %></em></p>
<% end %>