emarket/config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/create'
  get 'password_resets/edit'
  get 'password_resets/update'
  root 'home#index'

  get '/auth/google_oauth2', to: 'auth#google', as: :google_auth
  get '/auth/google_oauth2/callback', to: 'auth#callback'
  get '/auth/failure', to: 'auth#failure'

  get 'profilo/seguiti', to: 'acquirentes#seguiti', as: :acquirente_seguiti
  get 'follows/create'
  get 'follows/destroy'
  get 'feedbacks/new'
  get 'feedbacks/create'
  get 'return_requests/index'
  get 'return_requests/new'
  get 'return_requests/create'
  get 'return_requests/show'
  get 'return_requests/update'

  get 'ordini_negozi/index'
  get 'ordini_negozi/show'
  get 'ordini_negozi/update'

  get 'gestione_feedback/show'
  get 'gestione_account', to: 'gestione_account#manage'
  get 'statistiche', to: 'statistiche#show'
  get 'signup', to: 'acquirentes#new', as: 'signup'
  get 'admin_signup', to: 'amministratores#new', as: 'admin_signup'

  get 'amministratore/statistiche', to: 'amministratores#statistiche', as: :statistiche_amministratore

  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy', as: 'logout'

  get 'lista_desideri', to: 'lista_desideri#index'
  post 'add_to_wishlist/:id', to: 'lista_desideri#add', as: 'add_to_wishlist'
  delete 'remove_from_wishlist/:id', to: 'lista_desideri#remove', as: 'remove_from_wishlist'

  get 'archivio ordini', to: 'archivio_ordini#index', as: 'archivio_ordini'
  get 'cronologiaricerche', to: 'cronologia_ricerche#index', as: 'cronologia_ricerche'
  delete 'cronologia_ricerche', to: 'cronologia_ricerche#destroy', as: :cancella_cronologia


 
  get "/lingua", to: "lingua#seleziona", as: :lingua
  post "/lingua/cambia", to: "lingua#cambia", as: :cambia_lingua


  get 'admin/feedbacks_segnalati', to: 'amministratores#feedbacks_segnalati', as: 'admin_feedbacks_segnalati'
  delete 'gestione_account/ignora_segnalazione_negozio/:id', to: 'gestione_account#ignora_segnalazione_negozio', as: 'ignora_segnalazione_negozio'



  resources :segnalazioni, only: [:index, :destroy]
  resources :negozios do
    resources :ordini, controller: 'ordini_negozi', only: [:index, :show, :update]
    post 'follow', to: 'follows#create'
    delete 'unfollow', to: 'follows#destroy'
    resources :prodottos, only: [:new, :create]
    member do
      get :statistiche
      get 'recensioni', to: 'recensioninegozio#index'
      get 'feedbacks', to: 'negozios#feedbacks'
      get 'visualizza', to: 'negozios#visualizza'
      get 'seguaci'
      get :segnala_form
      post :segnala
      delete '/segnalazioni/:id/ignora', to: 'segnalazioni#ignora', as: :segnala_ignora
    end
  end


  resources :prodotti do
    resources :statistiche, only: [:index, :show]
  end

  resources :promoziones do
    collection do
      get 'admin'
      get 'negozio'
    end
  end

  resources :categorias, only: [:show]
  resources :prodottos
  resources :recensiones
  resources :variantis
  resources :acquirentes do
    member do
      get 'visualizza'
    end
  end
  
  resources :amministratores, only: [:create, :show, :edit, :update]

  resources :faqs do
    collection do
      get 'admin'
    end
  end

  resources :chat_rooms, only: [:index, :show, :new, :create, :destroy ] do
    post 'messages', to: 'chat_rooms#create_message', as: :messages
    post :start, on: :collection
    post :assistenza, on: :collection
  end

  resource :carrello, only: :show
  resources :carrello_items, only: [:create, :destroy]

  resources :ordini, only: [:new, :create, :show, :index] do
    collection do
      get 'successo', to: 'ordini#successo'
      get 'errore', to: 'ordini#errore'
    end
    post :annulla, on: :member
    post :pagamento, on: :member
    resources :return_requests, only: [:new, :create]
  end

  resources :return_requests, only: [:index, :show, :new, :create, :update]

  resources :negozio_return_requests, only: [:show, :index, :create] do
    member do
      patch :approve
      patch :reject
    end
  end

  resources :gestione_account, only: [:index] do
    member do
      patch :blocca
      patch :sblocca
      delete :elimina
      delete :elimina_negozio
    end
  end

  resources :feedbacks do
    member do
      patch :segnala
      patch :ignora_segnalazione
    end
  end

  resources :password_resets, only: [:new, :create, :edit, :update]

  
  # Monta Action Cable
  mount ActionCable.server => '/cable'
end

emarket/app/models/promozione.rb
class Promozione < ApplicationRecord
  belongs_to :negozio, optional: true
  belongs_to :prodotto, optional: true
  belongs_to :categorium, optional: true

  validates :nome, :descrizione, :inizio, :fine, :sconto, :tipo, presence: true
  validates :prodotto_id, presence: true, if: -> { tipo == 'singolo_prodotto' }
  validates :categorium_id, presence: true, if: -> { tipo == 'categoria' }
  validates :created_by, presence: true
  validates :tipo, inclusion: { in: %w[singolo_prodotto intero_sito categoria] }

  validate :correct_association

  private

  def correct_association
    case tipo
    when 'singolo_prodotto'
      errors.add(:prodotto, 'must be present for singolo_prodotto') unless prodotto_id.present?
    when 'categoria'
      errors.add(:categorium, 'must be present for categoria') unless categorium_id.present?
    when 'intero_sito'
      errors.add(:negozio, 'must be present for intero_sito') if negozio_id.present?
    end
  end
  
end

emarket/app/controllers/promoziones_controller.rb
class PromozionesController < ApplicationController
    before_action :set_promozione, only: %i[show edit update destroy]
    
    before_action :authorize_negozio_or_admin, only: %i[create new edit update destroy]

    before_action :authorize_promozione_owner, only: %i[edit update destroy]

  
    # GET /promoziones or /promoziones.json
    def index
      @promoziones = Promozione.all
    end
  
    # GET /promoziones/1 or /promoziones/1.json
    def show
    end

    def admin
      @promoziones = Promozione.where(created_by: 'admin')
    end

    def negozio
      @promoziones = Promozione.where(negozio: current_user.negozio)
    end
  
    # GET /promoziones/new
    def new
      @promozione = Promozione.new
    end
  
    # GET /promoziones/1/edit
    def edit
    end
  
    # POST /promoziones or /promoziones.json
    def create
      @promozione = Promozione.new(promozione_params)
      if current_user.is_a?(Acquirente) && current_user.negozio.present?
        @promozione.negozio = current_user.negozio
        @promozione.created_by = 'negozio'
        @promozione.tipo = 'singolo_prodotto'
      elsif current_user.is_a?(Amministratore)
        @promozione.created_by = 'admin'
      end
    
      respond_to do |format|
        if @promozione.save
          path = current_user.is_a?(Amministratore) ? admin_promoziones_path : negozio_promoziones_path
          format.html { redirect_to path, notice: 'Promozione creata con successo.' }
          format.json { render :show, status: :created, location: @promozione }
        else
          format.html { render :new }
          format.json { render json: @promozione.errors, status: :unprocessable_entity }
        end
      end
    end
    
  
    # PATCH/PUT /promoziones/1 or /promoziones/1.json
    def update
      respond_to do |format|
        if @promozione.update(promozione_params)
          path = current_user.is_a?(Amministratore) ? admin_promoziones_path : negozio_promoziones_path
          format.html { redirect_to path, notice: 'Promozione aggiornata con successo.' }
          format.json { render :show, status: :ok, location: @promozione }
        else
          format.html { render :edit }
          format.json { render json: @promozione.errors, status: :unprocessable_entity }
        end
      end
    end
    
  
    # DELETE /promoziones/1 or /promoziones/1.json
    def destroy
      @promozione.destroy
      respond_to do |format|
        format.html { redirect_to promoziones_url, notice: 'Promozione eliminata con successo.' }
        format.json { head :no_content }
      end
    end
  
    private
  
    def set_promozione
      @promozione = Promozione.find(params[:id])
    end
  
    def promozione_params
      params.require(:promozione).permit(:nome, :descrizione, :inizio, :fine, :sconto, :tipo, :prodotto_id, :categorium_id)
    end
  
    def authorize_negozio_or_admin
      unless current_user.is_a?(Amministratore) || (current_user.is_a?(Acquirente) && current_user.negozio.present?)
        redirect_to root_path, alert: 'Accesso negato: questa pagina è riservata agli amministratori o ai negozi.'
      end
    end

    def authorize_promozione_owner
      if @promozione.created_by == 'negozio'
        unless current_user.is_a?(Acquirente) && current_user.negozio == @promozione.negozio
          redirect_to root_path, alert: 'Non sei autorizzato a modificare questa promozione.'
        end
      elsif @promozione.created_by == 'admin'
        unless current_user.is_a?(Amministratore)
          redirect_to root_path, alert: 'Solo un amministratore può modificare questa promozione.'
        end
      else
        redirect_to root_path, alert: 'Accesso non autorizzato.'
      end
    end
    
  end
  

emarket/app/helpers/promoziones_helper.rb
module PromozionesHelper
end

emarket/app/views/promoziones/_form.html.erb
<%= stylesheet_link_tag 'app', media: 'all' %>

<%= form_with(model: promozione, local: true) do |form| %>
  <% if promozione.errors.any? %>
  <div class="alert alert-danger border border-danger shadow-sm rounded p-3 mb-4">
  <h4 class="alert-heading"><%= t("errors.messages.missing_fields") %>:</h4>
  <ul class="mb-0">
    <% promozione.errors.attribute_names.uniq.each do |attribute| %>
      <li><%= Promozione.human_attribute_name(attribute) %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome, t("comune.nome") %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :descrizione, t("forms.descrizione") %>
    <%= form.text_area :descrizione %>
  </div>

  <div class="field">
    <%= form.label :inizio, t("promo.inizio") %>
    <%= form.datetime_select :inizio %>
  </div>

  <div class="field">
    <%= form.label :fine, t("promo.fine") %>
    <%= form.datetime_select :fine %>
  </div>

  <div class="field">
    <%= form.label :sconto, t("promo.sconto") %>
    <%= form.number_field :sconto, step: 0.01 %>
  </div>

  <% if current_user.is_a?(Amministratore) %>
    <div class="field">
      <%= form.label :tipo, t("promo.tipo") %>
      <%= form.select :tipo, options_for_select([[t("promo.sito"), 'intero_sito'], [t("promo.cat"), 'categoria']], selected: promozione.tipo), id: 'promozione_tipo' %>
    </div>

    <div class="field" id="prodotto_field">
      <%= form.label :prodotto_id, t("comune.prodotto") %>
      <%= form.select :prodotto_id, options_for_select([[t("promo.sel_p"), ""]] + translated_prodotti_options) %>    </div>

    <div class="field" id="categoria_field">
      <%= form.label :categorium_id, t("promo.cat") %>
      <%= form.select :categorium_id, options_for_select([[t("promo.sel_c"), ""]] + translated_categorie_options) %>    </div>
  <% elsif current_user.is_a?(Acquirente) && current_user.negozio.present? %>
    <div class="field">
      <%= form.hidden_field :tipo, value: 'singolo_prodotto' %>
      <%= form.label :prodotto_id, t("comune.prodotto") %>
      <%= form.select :prodotto_id, options_for_select([[t("promo.sel_p"), ""]] + translated_negozio_prodotti_options(current_user.negozio)) %>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit promozione.persisted? ? t("promo.edit") : t("promo.aggiungi") %>
  </div>
<% end %>

<script>
  document.addEventListener('DOMContentLoaded', function() {
    function toggleFields() {
      var tipo = document.getElementById('promozione_tipo').value;
      var prodottoField = document.getElementById('prodotto_field');
      var categoriaField = document.getElementById('categoria_field');

      if (tipo === 'intero_sito') {
        prodottoField.style.display = 'none';
        categoriaField.style.display = 'none';
      } else if (tipo === 'singolo_prodotto') {
        prodottoField.style.display = 'block';
        categoriaField.style.display = 'none';
      } else if (tipo === 'categoria') {
        prodottoField.style.display = 'none';
        categoriaField.style.display = 'block';
      }
    }

    document.getElementById('promozione_tipo').addEventListener('change', toggleFields);
    toggleFields();
  });
</script>

emarket/app/views/promoziones/admin.html.erb
<%= stylesheet_link_tag 'app', media: 'all' %>
<p id="notice"><%= t_google(notice) %></p>

<main class="promo-container">
  <h1 class="promo-header"><%= t('promo.admin') %></h1>

  <table class="promo-table">
    <thead>
      <tr>
        <th><%= t('comune.nome') %></th>
        <th><%= t('promo.sconto') %></th>
        <th><%= t('promo.periodo') %></th>
        <th><%= t('promo.appl') %></th>
        <th><%= t('comune.azioni') %></th>
      </tr>
    </thead>
    <tbody>
      <% @promoziones.each do |promozione| %>
        <tr>
          <td>
            <strong><%= t_google(promozione.nome) %></strong><br>
            <small><%= t_google(promozione.descrizione) %></small>
          </td>
          <td><%= number_to_percentage(promozione.sconto, precision: 2) %></td>
          <td><%= promozione.inizio.strftime("%d %b %Y") %> - <%= promozione.fine.strftime("%d %b %Y") %></td>
          <td>
            <% if promozione.prodotto.present? %>
              <%= t('comune.prodotto') %>: <%= t_google(promozione.prodotto.nome_prodotto) %>
            <% elsif promozione.categorium.present? %>
              <%= t('promo.cat') %>: <%= t_google(promozione.categorium.nome) %>
            <% else %>
              <%= t('promo.tutto') %>
            <% end %>
          </td>
          <td class="promo-actions">
            <%= link_to t('comune.modifica'), edit_promozione_path(promozione), class: 'btn-action btn-edit' %>
            <%= button_to t('comune.elimina'), promozione, method: :delete, data: { confirm: t('comune.conferma'), turbo: false }, class: 'btn-action btn-delete' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="promo-footer">
    <%= link_to t('promo.aggiungi'), new_promozione_path, class: 'btn-action btn-add' %>
  </div>
</main>

emarket/app/views/promoziones/edit.html.erb
<%= stylesheet_link_tag 'app', media: 'all' %>

<p id="notice"><%= t_google(notice) %></p>
<h1><%= t('promo.edit') %></h1>

<%= render 'form', promozione: @promozione %>

emarket/app/views/promoziones/index.html.erb
<%= stylesheet_link_tag 'app', media: 'all' %>

<p id="notice"><%= t_google(notice) %></p>
<div class="container mt-5">
  <h1 class="mb-4 text-center"><%= t('promo.index') %></h1>
  <div class="row">
    <% @promoziones.each do |promozione| %>
      <div class="col-md-4">
        <div class="card mb-4 shadow-sm">
          <div class="card-body">
            <h5 class="card-title"><%= t_google(promozione.nome) %></h5>
            <p class="card-text"><%= t_google(promozione.descrizione) %></p>
            <ul class="list-unstyled">
              <li><strong><%= t('promo.inizio') %>:</strong> <%= promozione.inizio.strftime('%d/%m/%Y') %></li>
              <li><strong><%= t('promo.fine') %>:</strong> <%= promozione.fine.strftime('%d/%m/%Y') %></li>
              <li><strong><%= t('promo.sconto') %>:</strong> <%= number_to_percentage(promozione.sconto , precision: 2) %></li>
            </ul>
            <p class="card-text">
            <% if promozione.prodotto.present? %>
              <%= link_to t('promo.vedi_prod'), prodotto_path(promozione.prodotto), class: 'btn btn-primary' %>
            <% elsif promozione.categorium.present? %>
              <%= link_to t('promo.vedi_cat'), categoria_path(promozione.categorium), class: 'btn btn-success' %>
            <% else %>
              <span class="text-muted"><%= t('promo.no_p_c') %></span>
            <% end %>
          </p>
            </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

emarket/app/views/promoziones/negozio.html.erb
<%= stylesheet_link_tag 'app', media: 'all' %>
<p id="notice"><%= t_google(notice) %></p>

<main class="promo-container">
  <h1 class="promo-header"><%= t('promo.negozio') %></h1>

  <table class="promo-table">
    <tbody>
      <% @promoziones.each do |promozione| %>
        <tr>
          <td>
            <strong><%= t_google(promozione.nome) %></strong><br>
            <%= t_google(promozione.descrizione) %>
          </td>
          <td><%= number_to_percentage(promozione.sconto, precision: 2) %></td>
          <td><%= promozione.inizio.strftime("%d %b %Y") %> - <%= promozione.fine.strftime("%d %b %Y") %></td>
          <td>
            <% if promozione.prodotto.present? %>
              <%= t('comune.prodotto') %>: <%= t_google(promozione.prodotto.nome_prodotto) %>
            <% elsif promozione.categorium.present? %>
              <%= t('promo.cat') %>: <%= t_google(promozione.categorium.nome) %>
            <% else %>
              <%= t('promo.tutto') %>
            <% end %>
          </td>
          <td class="promo-actions">
            <%= link_to t('comune.modifica'), edit_promozione_path(promozione), class: 'btn-action btn-edit' %>
            <%= button_to t('comune.elimina'), promozione, method: :delete, data: { confirm: t('comune.conferma'), turbo: false }, class: 'btn-action btn-delete' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="promo-footer">
    <%= link_to t('promo.aggiungi'), new_promozione_path, class: 'btn-action btn-add' %>
  </div>
</main>

emarket/app/views/promoziones/new.html.erb
<%= stylesheet_link_tag 'app', media: 'all' %>

<p id="notice"><%= t_google(notice) %></p>
<h1><%= t('promo.new') %></h1>

<%= render 'form', promozione: @promozione %>

emarket/app/views/promoziones/show.html.erb
<p>
  <strong>Nome:</strong>
  <%= @promozione.nome %>
</p>

<p>
  <strong>Descrizione:</strong>
  <%= @promozione.descrizione %>
</p>

<p>
  <strong>Inizio:</strong>
  <%= @promozione.inizio %>
</p>

<p>
  <strong>Fine:</strong>
  <%= @promozione.fine %>
</p>

<p>
  <strong>Sconto:</strong>
  <%= number_to_percentage(@promozione.sconto * 100, precision: 2) %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @promozione.tipo %>
</p>

<p>
  <strong>Prodotto:</strong>
  <%= @promozione.prodotto&.nome_prodotto %>
</p>

<p>
  <strong>Categoria:</strong>
  <%= @promozione.categorium&.nome %>
</p>