emarket/config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/create'
  get 'password_resets/edit'
  get 'password_resets/update'
  root 'home#index'

  get '/auth/google_oauth2', to: 'auth#google', as: :google_auth
  get '/auth/google_oauth2/callback', to: 'auth#callback'
  get '/auth/failure', to: 'auth#failure'

  get 'profilo/seguiti', to: 'acquirentes#seguiti', as: :acquirente_seguiti
  get 'follows/create'
  get 'follows/destroy'
  get 'feedbacks/new'
  get 'feedbacks/create'
  get 'return_requests/index'
  get 'return_requests/new'
  get 'return_requests/create'
  get 'return_requests/show'
  get 'return_requests/update'

  get 'ordini_negozi/index'
  get 'ordini_negozi/show'
  get 'ordini_negozi/update'

  get 'gestione_feedback/show'
  get 'gestione_account', to: 'gestione_account#manage'
  get 'statistiche', to: 'statistiche#show'
  get 'signup', to: 'acquirentes#new', as: 'signup'
  get 'admin_signup', to: 'amministratores#new', as: 'admin_signup'

  get 'amministratore/statistiche', to: 'amministratores#statistiche', as: :statistiche_amministratore

  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy', as: 'logout'

  get 'lista_desideri', to: 'lista_desideri#index'
  post 'add_to_wishlist/:id', to: 'lista_desideri#add', as: 'add_to_wishlist'
  delete 'remove_from_wishlist/:id', to: 'lista_desideri#remove', as: 'remove_from_wishlist'

  get 'archivio ordini', to: 'archivio_ordini#index', as: 'archivio_ordini'
  get 'cronologiaricerche', to: 'cronologia_ricerche#index', as: 'cronologia_ricerche'
  delete 'cronologia_ricerche', to: 'cronologia_ricerche#destroy', as: :cancella_cronologia


 
  get "/lingua", to: "lingua#seleziona", as: :lingua
  post "/lingua/cambia", to: "lingua#cambia", as: :cambia_lingua


  get 'admin/feedbacks_segnalati', to: 'amministratores#feedbacks_segnalati', as: 'admin_feedbacks_segnalati'
  delete 'gestione_account/ignora_segnalazione_negozio/:id', to: 'gestione_account#ignora_segnalazione_negozio', as: 'ignora_segnalazione_negozio'



  resources :segnalazioni, only: [:index, :destroy]
  resources :negozios do
    resources :ordini, controller: 'ordini_negozi', only: [:index, :show, :update]
    post 'follow', to: 'follows#create'
    delete 'unfollow', to: 'follows#destroy'
    resources :prodottos, only: [:new, :create]
    member do
      get :statistiche
      get 'recensioni', to: 'recensioninegozio#index'
      get 'feedbacks', to: 'negozios#feedbacks'
      get 'visualizza', to: 'negozios#visualizza'
      get 'seguaci'
      get :segnala_form
      post :segnala
      delete '/segnalazioni/:id/ignora', to: 'segnalazioni#ignora', as: :segnala_ignora
    end
  end


  resources :prodotti do
    resources :statistiche, only: [:index, :show]
  end

  resources :promoziones do
    collection do
      get 'admin'
      get 'negozio'
    end
  end

  resources :categorias, only: [:show]
  resources :prodottos
  resources :recensiones
  resources :variantis
  resources :acquirentes do
    member do
      get 'visualizza'
    end
  end
  
  resources :amministratores, only: [:create, :show, :edit, :update]

  resources :faqs do
    collection do
      get 'admin'
    end
  end

  resources :chat_rooms, only: [:index, :show, :new, :create, :destroy ] do
    post 'messages', to: 'chat_rooms#create_message', as: :messages
    post :start, on: :collection
    post :assistenza, on: :collection
  end

  resource :carrello, only: :show
  resources :carrello_items, only: [:create, :destroy]

  resources :ordini, only: [:new, :create, :show, :index] do
    collection do
      get 'successo', to: 'ordini#successo'
      get 'errore', to: 'ordini#errore'
    end
    post :annulla, on: :member
    post :pagamento, on: :member
    resources :return_requests, only: [:new, :create]
  end

  resources :return_requests, only: [:index, :show, :new, :create, :update]

  resources :negozio_return_requests, only: [:show, :index, :create] do
    member do
      patch :approve
      patch :reject
    end
  end

  resources :gestione_account, only: [:index] do
    member do
      patch :blocca
      patch :sblocca
      delete :elimina
      delete :elimina_negozio
    end
  end

  resources :feedbacks do
    member do
      patch :segnala
      patch :ignora_segnalazione
    end
  end

  resources :password_resets, only: [:new, :create, :edit, :update]

  
  # Monta Action Cable
  mount ActionCable.server => '/cable'
end

emarket/app/models/amministratore.rb
class Amministratore < ApplicationRecord
    has_secure_password

    has_many :messaggi_inviati, as: :mittente, class_name: 'Messaggio'
    has_many :messaggi_ricevuti, as: :destinatario, class_name: 'Messaggio'

    validates :email, presence: true, uniqueness: true
    validates :password, presence: true, length: { minimum: 6 }, if: -> { new_record? || !password.nil? }

    def nome_completo
        "#{nome} #{cognome}"
    end

    def self.designato
        find_by(email: 'giovanni.neri@example.com') || first
      end

    
end

emarket/app/controllers/amministratores_controller.rb
class AmministratoresController < ApplicationController
  before_action :set_amministratore, only: %i[ show edit update destroy ]
  before_action :authenticate_amministratore!, only: %i[ show edit update destroy ]
  before_action :authorize_amministratore, only: %i[ show edit update destroy ]

  
  def index
    @amministratores = Amministratore.all
  end

  
  def show
    @amministratore = Amministratore.find(params[:id])
  end

  
  def new
    @amministratore = Amministratore.new
  end

  
  def edit
  end

  
  def create
    @amministratore = Amministratore.new(amministratore_params)

    if @amministratore.save
      session[:user_id] = @amministratore.id
      session[:role] = 'amministratore'
      redirect_to root_path, notice: "Registrazione completata!"
    else
      render :new
    end

    respond_to do |format|
      if @amministratore.save
        format.html { redirect_to amministratore_url(@amministratore), notice: "Amministratore was successfully created." }
        format.json { render :show, status: :created, location: @amministratore }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @amministratore.errors, status: :unprocessable_entity }
      end
    end
  end

  
  def update
    respond_to do |format|
      if @amministratore.update(amministratore_params)
        format.html { redirect_to @amministratore, notice: "Amministratore aggiornato con successo." }
        format.json { render :show, status: :ok, location: @amministratore }
      else
        format.html { render :edit }
        format.json { render json: @amministratore.errors, status: :unprocessable_entity }
      end
    end
  end

  
  def destroy
    @amministratore.destroy

    respond_to do |format|
      format.html { redirect_to amministratores_url, notice: "Amministratore was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def feedbacks_segnalati
    @feedbacks = Feedback.where(segnalato: true).includes(:acquirente, :prodotto)
  end

  def statistiche
    @acquirenti_totali = Acquirente.count
    @venditori_totali = Negozio.count
  
    @acquirenti_corrente_mese = Acquirente.where(created_at: Time.current.beginning_of_month..Time.current.end_of_month).count
    @venditori_corrente_mese = Negozio.where(created_at: Time.current.beginning_of_month..Time.current.end_of_month).count
  
    @acquirenti_corrente_anno = Acquirente.where(created_at: Time.current.beginning_of_year..Time.current.end_of_year).count
    @venditori_corrente_anno = Negozio.where(created_at: Time.current.beginning_of_year..Time.current.end_of_year).count
  
    @vendite_totali = Ordine.count
    @media_acquisti_per_acquirente = Ordine.group(:acquirente_id).count.values.sum.to_f / Acquirente.count rescue 0
  
    @media_articoli_per_ordine = Ordine.joins(:ordine_items).group(:id).count.values.sum.to_f / Ordine.count rescue 0
  
    acquirenti_con_almeno_un_ordine = Acquirente.joins(:ordini).distinct.count
    acquirenti_senza_ordini = Acquirente.count - acquirenti_con_almeno_un_ordine
    @rapporto_acquirenti_0_vs_1plus = {
      con_ordini: acquirenti_con_almeno_un_ordine,
      senza_ordini: acquirenti_senza_ordini
    }
  
    @media_prodotti_per_venditore = Negozio.joins(:prodottos).group(:id).count.values.sum.to_f / Negozio.count rescue 0
  
    @media_guadagno_per_venditore = Negozio.all.map do |negozio|
      negozio.prodottos.joins(:ordine_items).sum("ordine_items.prezzo * ordine_items.quantity")
    end.sum.to_f / Negozio.count rescue 0
  
    @media_spesa_per_acquirente = Acquirente.all.map do |acq|
      acq.ordini.joins(:ordine_items).sum("ordine_items.prezzo * ordine_items.quantity")
    end.sum.to_f / Acquirente.count rescue 0
  end
  

  private
    
    def set_amministratore
      @amministratore = Amministratore.find(params[:id])
    end

    
    def amministratore_params
  
    params.require(:amministratore).permit(:nome, :cognome, :email, :password, :password_confirmation)
    end

    def authorize_amministratore
      unless current_user == @amministratore
        redirect_to root_path, alert: "Accesso negato: non sei autorizzato ad accedere a questa pagina." and return
      end
    end
end

emarket/app/helpers/amministratores_helper.rb
module AmministratoresHelper
end

emarket/app/views/amministratores/_form.html.erb
<%= stylesheet_link_tag 'app', media: 'all' %>

<%= form_with(model: amministratore) do |form| %>
  <% if amministratore.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(amministratore.errors.count, t("errors.messages.error")) %> <%= t("errors.messages.prevented_save") %></h2>

      <ul>
        <% amministratore.errors.each do |error| %>
          <li><%= t_google(error.full_message) %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= t_google(form.submit) %>
  </div>
<% end %>

emarket/app/views/amministratores/edit.html.erb
<%= stylesheet_link_tag 'app', media: 'all' %>

<p><%= t_google(notice) %></p>
<h1><%= t('comune.mod_prof')%></h1>

<%= form_with(model: @amministratore, local: true) do |form| %>
  <div>
    <%= form.label :nome, t("forms.nome") %>
    <%= form.text_field :nome %>
  </div>

  <div>
    <%= form.label :cognome, t("forms.cognome") %>
    <%= form.text_field :cognome %>
  </div>

  <div>
    <%= form.label :telefono, t("forms.telefono") %>
    <%= form.text_field :telefono %>
  </div>

  <div>
    <%= form.label :email, t("forms.email") %>
    <%= form.email_field :email %>
  </div>

  <div>
    <%= form.label :password, t("forms.password") %>
    <%= form.password_field :password %>
  </div>

  <div>
    <%= form.label :password_confirmation, t("forms.password_confirmation") %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div>
    <%= form.submit t("forms.save"), class: "btn btn-primary" %>
    <%= link_to t("forms.cancel"), amministratore_path(@amministratore), class: "btn" %>
  </div>
<% end %>

emarket/app/views/amministratores/feedbacks_segnalati.html.erb
<%= stylesheet_link_tag 'app', media: 'all' %>

<p><%= t_google(notice) %></p>

<h1><%= t('amministratore.f_titolo') %></h1>

<% if @feedbacks.any? %>
  <table class="table">
    <thead>
      <tr>
        <th><%= t('comune.prodotto') %></th>
        <th><%= t('comune.acquirente') %></th>
        <th><%= t('amministratore.f_voto') %></th>
        <th><%= t('comune.nota') %></th>
        <th><%= t('comune.azioni') %></th>
      </tr>
    </thead>
    <tbody>
      <% @feedbacks.each do |feedback| %>
        <tr>
          <td><%= feedback.prodotto.nome_prodotto %></td>
          <td><%= feedback.acquirente&.nome || t('amministratore.f_utente_eliminato') %></td>
          <td><%= feedback.voto %> ★</td>
          <td><%= feedback.nota.presence || t('comune.no_nota') %></td>
          <td>
            <%= button_to t('amministratore.f_elimina'), 
              feedback_path(feedback, redirect_to: gestione_account_path), 
              method: :delete, 
              data: { confirm: t('amministratore.f_conferma') }, 
              class: "btn btn-danger" %>

            <%= button_to t('amministratore.f_ignora'), ignora_segnalazione_feedback_path(feedback), 
              method: :patch, class: "btn btn-secondary" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p><%= t('amministratore.no_feedback') %> </p>
<% end %>

emarket/app/views/amministratores/new.html.erb
<h1>New Amministratore</h1>

<%= render 'form', amministratore: @amministratore %>

<%= link_to 'Back', amministratores_path %>

emarket/app/views/amministratores/show.html.erb
<%= stylesheet_link_tag 'app', media: 'all' %>

<p><%= t_google(notice) %></p>

<div class="container mt-5">
  <div class="row">
    <div class="col-md-12 mb-4">
      <h1 class="text-center"><%= t('comune.profilo_amministratore') %></h1>
    </div>
  </div>

  <div class="row">
    <!-- Sidebar -->
    <div class="col-md-3">
      <nav class="nav flex-column nav-pills">
        <%= link_to t('amministratore.account'), gestione_account_path, class: 'nav-link btn btn-outline-primary mb-2' %>
        <%= link_to t('amministratore.statistiche'), statistiche_amministratore_path, class: 'nav-link btn btn-outline-primary mb-2' %>
        <%= link_to t('amministratore.feedback'), admin_feedbacks_segnalati_path, class: 'nav-link btn btn-outline-primary mb-2' %>
        <%= link_to t('amministratore.gest_faq'), admin_faqs_path, class: 'nav-link btn btn-outline-primary mb-2' %>
        <%= link_to t('amministratore.promo'), admin_promoziones_path, class: 'nav-link btn btn-outline-primary mb-2' %>
      </nav>
    </div>

    <!-- Main Content -->
    <div class="col-md-9">
      <!-- Admin Details -->
      <div class="card mb-4 shadow-sm">
        <div class="card-body">
          <h5 class="card-title"><%= t('comune.dettagli') %></h5>
          <p class="card-text"><strong><%= t('comune.nome') %></strong> <%= @amministratore.nome %> <%= @amministratore.cognome %></p>
          <p class="card-text"><strong><%= t('amministratore.id') %></strong> <%= @amministratore.id %></p>
          <p class="card-text"><strong><%= t('sessions.email') %>:</strong> <%= @amministratore.email %></p>
          <p class="card-text"><strong><%= t('comune.telefono') %></strong> <%= @amministratore.telefono %></p>
        </div>
      </div>

      <div class="d-flex justify-content-end">
        <%= link_to t('comune.mod_prof'), edit_amministratore_path(@amministratore), class: 'btn btn-warning me-2' %>
      </div>
    </div>
  </div>
</div>

emarket/app/views/amministratores/statistiche.html.erb
<%= stylesheet_link_tag 'app', media: 'all' %>

<p><%= t_google(notice) %></p>

<div class="admin-stats-container">

  <h1 class="admin-stats-title"><%= t('amministratore.s_titolo') %></h1>

  <div class="admin-card">
    <h2 class="admin-card-title"><%= t('amministratore.s_utenti') %></h2>
    <ul class="admin-list">
      <li><%= t('amministratore.s_acq_tot') %> <%= @acquirenti_totali %></li>
      <li><%= t('amministratore.s_vend_tot') %> <%= @venditori_totali %></li>
      <li><%= t('amministratore.s_acq_mese') %> <%= @acquirenti_corrente_mese %></li>
      <li><%= t('amministratore.s_vend_mese') %> <%= @venditori_corrente_mese %></li>
      <li><%= t('amministratore.s_acq_anno') %> <%= @acquirenti_corrente_anno %></li>
      <li><%= t('amministratore.s_vend_anno') %> <%= @venditori_corrente_anno %></li>
    </ul>
  </div>

  <div class="admin-card">
    <h2 class="admin-card-title"><%= t('amministratore.s_ord_ven') %></h2>
    <ul class="admin-list">
      <li><%= t('amministratore.s_ven_tot') %> <%= @vendite_totali %></li>
      <li><%= t('amministratore.s_med_acq') %> <%= number_with_precision(@media_acquisti_per_acquirente, precision: 2) %></li>
      <li><%= t('amministratore.s_med_art') %> <%= number_with_precision(@media_articoli_per_ordine, precision: 2) %></li>
    </ul>
  </div>

  <div class="admin-card">
    <h2 class="admin-card-title"><%= t('amministratore.s_acq') %></h2>
    <ul class="admin-list">
      <li><%= t('amministratore.s_acq1') %> <%= @rapporto_acquirenti_0_vs_1plus[:con_ordini] %></li>
      <li><%= t('amministratore.s_acq0') %> <%= @rapporto_acquirenti_0_vs_1plus[:senza_ordini] %></li>
      <li><%= t('amministratore.s_med_spesa') %> <%= number_to_currency(@media_spesa_per_acquirente) %></li>
    </ul>
  </div>

  <div class="admin-card">
    <h2 class="admin-card-title"><%= t('amministratore.s_vend') %></h2>
    <ul class="admin-list">
      <li><%= t('amministratore.s_med_prod') %> <%= number_with_precision(@media_prodotti_per_venditore, precision: 2) %></li>
      <li><%= t('amministratore.s_med_guadagno') %> <%= number_to_currency(@media_guadagno_per_venditore) %></li>
    </ul>
  </div>

</div>