emarket/config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/create'
  get 'password_resets/edit'
  get 'password_resets/update'
  root 'home#index'

  get '/auth/google_oauth2', to: 'auth#google', as: :google_auth
  get '/auth/google_oauth2/callback', to: 'auth#callback'
  get '/auth/failure', to: 'auth#failure'

  get 'profilo/seguiti', to: 'acquirentes#seguiti', as: :acquirente_seguiti
  get 'follows/create'
  get 'follows/destroy'
  get 'feedbacks/new'
  get 'feedbacks/create'
  get 'return_requests/index'
  get 'return_requests/new'
  get 'return_requests/create'
  get 'return_requests/show'
  get 'return_requests/update'

  get 'ordini_negozi/index'
  get 'ordini_negozi/show'
  get 'ordini_negozi/update'

  get 'gestione_feedback/show'
  get 'gestione_account', to: 'gestione_account#manage'
  get 'statistiche', to: 'statistiche#show'
  get 'signup', to: 'acquirentes#new', as: 'signup'
  get 'admin_signup', to: 'amministratores#new', as: 'admin_signup'

  get 'amministratore/statistiche', to: 'amministratores#statistiche', as: :statistiche_amministratore

  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy', as: 'logout'

  get 'lista_desideri', to: 'lista_desideri#index'
  post 'add_to_wishlist/:id', to: 'lista_desideri#add', as: 'add_to_wishlist'
  delete 'remove_from_wishlist/:id', to: 'lista_desideri#remove', as: 'remove_from_wishlist'

  get 'archivio ordini', to: 'archivio_ordini#index', as: 'archivio_ordini'
  get 'cronologiaricerche', to: 'cronologia_ricerche#index', as: 'cronologia_ricerche'
  delete 'cronologia_ricerche', to: 'cronologia_ricerche#destroy', as: :cancella_cronologia


 
  get "/lingua", to: "lingua#seleziona", as: :lingua
  post "/lingua/cambia", to: "lingua#cambia", as: :cambia_lingua


  get 'admin/feedbacks_segnalati', to: 'amministratores#feedbacks_segnalati', as: 'admin_feedbacks_segnalati'
  delete 'gestione_account/ignora_segnalazione_negozio/:id', to: 'gestione_account#ignora_segnalazione_negozio', as: 'ignora_segnalazione_negozio'



  resources :segnalazioni, only: [:index, :destroy]
  resources :negozios do
    resources :ordini, controller: 'ordini_negozi', only: [:index, :show, :update]
    post 'follow', to: 'follows#create'
    delete 'unfollow', to: 'follows#destroy'
    resources :prodottos, only: [:new, :create]
    member do
      get :statistiche
      get 'recensioni', to: 'recensioninegozio#index'
      get 'feedbacks', to: 'negozios#feedbacks'
      get 'visualizza', to: 'negozios#visualizza'
      get 'seguaci'
      get :segnala_form
      post :segnala
      delete '/segnalazioni/:id/ignora', to: 'segnalazioni#ignora', as: :segnala_ignora
    end
  end


  resources :prodotti do
    resources :statistiche, only: [:index, :show]
  end

  resources :promoziones do
    collection do
      get 'admin'
      get 'negozio'
    end
  end

  resources :categorias, only: [:show]
  resources :prodottos
  resources :recensiones
  resources :variantis
  resources :acquirentes do
    member do
      get 'visualizza'
    end
  end
  
  resources :amministratores, only: [:create, :show, :edit, :update]

  resources :faqs do
    collection do
      get 'admin'
    end
  end

  resources :chat_rooms, only: [:index, :show, :new, :create, :destroy ] do
    post 'messages', to: 'chat_rooms#create_message', as: :messages
    post :start, on: :collection
    post :assistenza, on: :collection
  end

  resource :carrello, only: :show
  resources :carrello_items, only: [:create, :destroy]

  resources :ordini, only: [:new, :create, :show, :index] do
    collection do
      get 'successo', to: 'ordini#successo'
      get 'errore', to: 'ordini#errore'
    end
    post :annulla, on: :member
    post :pagamento, on: :member
    resources :return_requests, only: [:new, :create]
  end

  resources :return_requests, only: [:index, :show, :new, :create, :update]

  resources :negozio_return_requests, only: [:show, :index, :create] do
    member do
      patch :approve
      patch :reject
    end
  end

  resources :gestione_account, only: [:index] do
    member do
      patch :blocca
      patch :sblocca
      delete :elimina
      delete :elimina_negozio
    end
  end

  resources :feedbacks do
    member do
      patch :segnala
      patch :ignora_segnalazione
    end
  end

  resources :password_resets, only: [:new, :create, :edit, :update]

  
  # Monta Action Cable
  mount ActionCable.server => '/cable'
end

emarket/app/models/negozio.rb
class Negozio < ApplicationRecord
    
    belongs_to :acquirente
    has_many :prodottos, dependent: :destroy
    has_many :promoziones, dependent: :destroy
    has_many :follows
    has_many :followers, through: :follows, source: :acquirente
    has_many :messaggi_inviati, as: :mittente, class_name: 'Messaggio', dependent: :destroy
    has_many :messaggi_ricevuti, as: :destinatario, class_name: 'Messaggio', dependent: :destroy
    has_many :segnalazioni_negozi, class_name: 'SegnalazioneNegozio', dependent: :destroy

    has_one_attached :immagine 

    validates :nome_negozio, :telefono, presence: true
    validate :immagine_must_be_variable

    def nome_completo
        nome_negozio
    end

    def immagine_must_be_variable
      if immagine.attached? && !immagine.variable?
        errors.add(:immagine, "non è un formato immagine valido o non può essere elaborata")
      end
    end
end

emarket/app/controllers/negozios_controller.rb
class NegoziosController < ApplicationController
  before_action :authenticate_acquirente!, except: [:visualizza]
  before_action :set_negozio, only: [:show, :edit, :update, :destroy, :visualizza, :statistiche, :seguaci]
  before_action :authorize_negozio, only: [:show, :edit, :update, :destroy, :statistiche, :seguaci]

  
  def index
    @negozios = Negozio.all
  end

  
  def show
    @acquirente = @negozio.acquirente
  end

  def visualizza
  end

  def seguaci
    @negozio = Negozio.find(params[:id])
    @seguaci = @negozio.followers
  end
  
  
  def new
    @negozio = current_user.build_negozio
  end

  
  def edit
  end

  
  def create
    @negozio = current_user.build_negozio(negozio_params)
    if @negozio.save
      redirect_to @negozio, notice: 'Negozio creato con successo!'
    else
      render :new
    end
  end

  
  def update
    respond_to do |format|
      if @negozio.update(negozio_params)
        format.html { redirect_to negozio_url(@negozio), notice: "Negozio modificato con successo." }
        format.json { render :show, status: :ok, location: @negozio }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @negozio.errors, status: :unprocessable_entity }
      end
    end
  end

  def feedbacks
    @negozio = Negozio.find(params[:id])
    @prodottos = @negozio.prodottos.includes(feedbacks: :acquirente)
  end
  

  
  def destroy
    @negozio.destroy

    respond_to do |format|
      format.html { redirect_to acquirente_path(current_user), notice: "Negozio cancellato con successo." }
      format.json { head :no_content }
    end
  end

  def statistiche
    @negozio = Negozio.find(params[:id])
    prodotti = @negozio.prodottos.includes(:ordine_items)
  
    ordine_items = prodotti.flat_map(&:ordine_items)
  
    # Statistiche generali
    @totale_vendite = ordine_items.sum(&:quantity)
    @guadagni_ultimo_mese = ordine_items.select { |oi| oi.created_at >= 1.month.ago }.sum { |oi| oi.quantity * oi.prezzo }
    @guadagni_ultimo_anno = ordine_items.select { |oi| oi.created_at >= 1.year.ago }.sum { |oi| oi.quantity * oi.prezzo }
    @prodotti_in_vendita = prodotti.count
    @media_prezzo = (@negozio.prodottos.average(:prezzo) || 0).to_f

  
    # Statistiche per prodotto
    @statistiche_per_prodotto = prodotti.map do |p|
      items = p.ordine_items
      {
        prodotto: p,
        venduti: items.sum(:quantity),
        disponibili: p.quantita_disponibile,
        venduti_ultimo_mese: items.where(created_at: 1.month.ago..Time.current).sum(:quantity),
        venduti_ultimo_anno: items.where(created_at: 1.year.ago..Time.current).sum(:quantity)
      }
    end
  end
  
  def segnala_form
    @negozio = Negozio.find(params[:id])
  end
  
  def segnala
    @negozio = Negozio.find(params[:id])
    @segnalazione = SegnalazioneNegozio.new(
      motivo: params[:motivo],
      note: params[:note],
      acquirente: current_user,
      negozio: @negozio
    )
  
    if @segnalazione.save
      redirect_to visualizza_negozio_path(@negozio), notice: "Segnalazione inviata con successo."
    else
      render :segnala_form, alert: "Errore nell'invio della segnalazione."
    end
  end
  
  

  private
  
    def set_negozio
      @negozio = Negozio.find(params[:id])
    end

    
    def negozio_params
      params.require(:negozio).permit(:nome_negozio, :descrizione, :indirizzo, :telefono, :immagine)
    end

    def authorize_negozio
      unless current_user == @negozio.acquirente
        redirect_to root_path, alert: "Accesso negato: non sei autorizzato ad accedere a questa pagina." and return
      end
    end
end

emarket/app/helpers/negozios_helper.rb
module NegoziosHelper
end

emarket/app/views/negozios/_form.html.erb
<%= stylesheet_link_tag 'app', media: 'all' %>


<%= form_with(model: @negozio, local: true) do |form| %>
  <% if @negozio.errors.any? %>
    <div class="alert alert-danger border border-danger shadow-sm rounded p-3 mb-4">
    <h4 class="alert-heading"><%= t("errors.messages.missing_fields") %>:</h4>
    <ul class="mb-0">
        <% @negozio.errors.attribute_names.uniq.each do |attribute| %>
          <li><%= Negozio.human_attribute_name(attribute) %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome, t("negozio.nome") %>
    <%= form.text_field :nome_negozio %>
  </div>

  <div class="field">
    <%= form.label :descrizione, t("forms.descrizione") %>
    <%= form.text_area :descrizione %>
  </div>

  <div class="field">
    <%= form.label :indirizzo, t("negozio.indirizzo") %>
    <%= form.text_field :indirizzo %>
  </div>

  <div class="field">
    <%= form.label :telefono, t("forms.telefono") %>
    <%= form.text_field :telefono %>
  </div>

  <div class="field mb-4">
      <%= form.label :immagine, t("negozio.immagine") %>
      <%= form.file_field :immagine, class: "form-control" %>
    </div>

  <div class="actions">
   <%= form.submit negozio.persisted? ? t("negozio.aggiorna") : t("negozio.new") %>
  </div>
<% end %>
</div>

emarket/app/views/negozios/edit.html.erb
<%= stylesheet_link_tag 'app', media: 'all' %>

<p><%= t_google(notice) %></p>
<h1><%= t('negozio.edit') =%></h1>

<%= render 'form', negozio: @negozio %>

<%= link_to t('forms.cancel'), @negozio %> 

emarket/app/views/negozios/feedbacks.html.erb
<%= stylesheet_link_tag 'app', media: 'all' %>

<p id="notice"><%= t_google(notice) %></p>
<h1><%= t('negozio.feedback') =%> - <%= @negozio.nome_negozio %></h1>

<% if @prodottos.empty? %>
  <p><%= t('negozio.no_prodotti') =%></p>
<% else %>
  <% @prodottos.each do |prodotto| %>
    <div class="card mb-4">
      <h2><%= t_google(prodotto.nome_prodotto) %></h2>

      <% if prodotto.feedbacks.any? %>
        <ul>
          <% prodotto.feedbacks.each do |feedback| %>
            <li>
              <strong><%= t('negozio.voto_f') =%>:</strong> <%= '★' * feedback.voto + '☆' * (5 - feedback.voto) %><br>
              <% if feedback.nota.present? %>
                <strong><%= t('comune.nota') =%>:</strong> <%= t_google(feedback.nota) %><br>
              <% end %>
              <em><%= t('comune.da') =%>: <%= feedback.acquirente&.nome || t("negozio.no_utente_f") %> | <%= t('comune.data') =%>: <%= feedback.created_at.strftime("%d/%m/%Y") %></em>

            </li>
            <% unless feedback.segnalato %>
                <%= button_to t("gest.segnala"), segnala_feedback_path(feedback), method: :patch, class: "btn btn-warning btn-sm", data: { confirm: "Sei sicuro di voler segnalare questo feedback?" } %>
            <% else %>
                <span class="badge bg-danger"><%= t("gest.segnala") =%></span>
            <% end %>

          <% end %>
        </ul>
      <% else %>
        <p><%= t('prodotto.no_feedback') =%></p>
      <% end %>
    </div>
  <% end %>
<% end %>

emarket/app/views/negozios/new.html.erb
<%= stylesheet_link_tag 'app', media: 'all' %>

<p id="notice"><%= t_google(notice) %></p>


    <h1><%= t('negozio.new') =%></h1>

    <%= render 'form', negozio: @negozio %>
    

emarket/app/views/negozios/segnala.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <main>
    <section>
      <h1>Segnala negozio</h1>
      <form action="<%= segnala_negozio_path(@negozio) %>" method="post">
        <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
        <div class="form-group">
          <label for="motivo">Motivazione</label>
          <select id="motivo" name="motivo">
            <option value="frodi">Frodi</option>
            <option value="contenuti_inappropriati">Contenuti inappropriati</option>
            <option value="altro">Altro</option>
          </select>
        </div>
        <div class="form-group">
          <label for="note">Note (opzionale)</label>
          <textarea id="note" name="note"></textarea>
        </div>
        <button type="submit">Invia</button>
        <button type="button" onclick="window.location='<%= negozio_path(@negozio) %>'">Annulla</button>
      </form>
    </section>
  </main>

  <%= javascript_include_tag 'https://code.jquery.com/jquery-3.3.1.slim.min.js', integrity: 'sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo', crossorigin: 'anonymous' %>
  <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js', integrity: 'sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGaZ5tgkIoGQjYI38tALe10aD5', crossorigin: 'anonymous' %>
  <%= javascript_include_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js', integrity: 'sha384-smHYkd5q/lz2INN2yjn3iycfw8KkxFO1EVc2TTzIT6EGGoebh9aJF4JG2PphfF7L', crossorigin: 'anonymous' %>
  <script>
    function toggleRightSideMenu() {
      var menu = document.getElementById("rightSideMenu");
      if (menu.style.display === "block") {
        menu.style.display = "none";
      } else {
        menu.style.display = "block";
      }
    }
  </script>
</body>
</html>

emarket/app/views/negozios/segnala_form.html.erb
<%= stylesheet_link_tag 'app', media: 'all' %>

<h1><%= t('segn_n.titolo') =%> "<%= @negozio.nome_negozio %>"</h1>

<%= form_with url: segnala_negozio_path(@negozio), method: :post, local: true do |form| %>
  <div>
    <%= form.label :motivo, t("segn_n.motivo") %><br>
    <%= form.select :motivo, [t("segn_n.m1"), t("segn_n.m2"), t("segn_n.m3"), t("segn_n.altro")], prompt: t("segn_n.sel"), required: true %>
  </div>

  <div>
    <%= form.label :note, t("segn_n.note") %><br>
    <%= form.text_area :note, rows: 4, placeholder: t("segn_n.spiega") %>
  </div>

  <div>
    <%= form.submit t("segn_n.invia"), class: "btn btn-danger" %>
    <%= link_to t("comune.annulla"), negozio_path(@negozio), class: "btn btn-secondary" %>
  </div>
<% end %>

emarket/app/views/negozios/seguaci.html.erb
<%= stylesheet_link_tag 'app', media: 'all' %>

<p id="notice"><%= t_google(notice) %></p>
<h2 class="text-center my-4"><%= t('negozio.seguaci_n') =%></h2>
<% @seguaci.each do |acquirente| %>
  <li class="list-group-item">
    <%= link_to acquirente.nome_completo, visualizza_acquirente_path(acquirente), class: "text-decoration-none" %>
  </li>
<% end %>

emarket/app/views/negozios/show.html.erb
<%= stylesheet_link_tag 'app', media: 'all' %>

<p id="notice"><%= t_google(notice) %></p>

<div class="container mt-5">
  <div class="row">
    <div class="col-md-12 mb-4">
      <h1 class="text-center"><%= t('comune.negozio') =%></h1>
    </div>
  </div>





  <div class="row">
    <!-- Sidebar -->
    <div class="col-md-3">
      <nav class="nav flex-column nav-pills">
        <%= link_to t('comune.statistiche'), statistiche_negozio_path(@negozio), class: 'nav-link btn btn-outline-primary mb-2' %>
        <%= link_to t('comune.promo'), negozio_promoziones_path, class: 'nav-link btn btn-outline-primary mb-2' %>
        <%= link_to t('negozio.aggiungi'), new_negozio_prodotto_path(@negozio), class: 'nav-link btn btn-outline-primary mb-2' %>
        <%= link_to t('comune.messaggi'), chat_rooms_path, class: 'nav-link btn btn-outline-primary mb-2' %>
        <%= link_to t('negozio.resi'), negozio_return_requests_path, class: 'nav-link btn btn-outline-primary mb-2' %>
        <%= link_to t('negozio.rec'), feedbacks_negozio_path(current_user.negozio), class: 'nav-link btn btn-outline-primary mb-2' %>
        <%= link_to t('negozio.ordini'), negozio_ordini_path(@negozio), class: 'nav-link btn btn-outline-primary mb-2' %>

      </nav>
    </div>

    <!-- Main Content -->
    <div class="col-md-9">
      <!-- Store Details -->
      <div class="card mb-4 shadow-sm">
        <div class="card-body">
          <h5 class="card-title"><%= t('negozio.dett') =%></h5>                                                                 
          <% if @negozio.immagine.attached? %>
          <div class="mb-3">
            <%= image_tag @negozio.immagine.variant(resize_to_limit: [300, 300]), class: "img-fluid rounded" %>
          </div>
        <% end %>
          <p class="card-text"><strong><%= t('negozio.nome') =%>:</strong> <%= @negozio.nome_negozio %></p>
          <p class="card-text"><strong><%= t('comune.email') =%>:</strong> <%= @acquirente.email %></p>
          <p class="card-text"><strong><%= t('comune.telefono') =%></strong> <%= @negozio.telefono %></p>
          <p class="card-text"><strong><%= t('negozio.proprietario') =%>:</strong> <%= @negozio.acquirente.nome_utente %></p>
          <p class="card-text">
          <%= link_to t('negozio.seguaci'), seguaci_negozio_path(@negozio), class: "btn btn-outline-primary" %>

          </p>
        </div>
      </div>

      <!-- Store Products -->
      <div class="card mb-4 shadow-sm">
        <div class="card-body">
          <h5 class="card-title"><%= t('negozio.prodotti') =%></h5>
          <% if @negozio.prodottos.present? %>
  <div class="row">
    <% @negozio.prodottos.each do |prodotto| %>
      <div class="col-md-4 mb-4">
        <div class="card h-100">
          <% if prodotto.immagini.attached? %>
          <%= image_tag prodotto.immagini.first.variant(resize_to_limit: [250, 250]), class: "card-img-top" %>
          <% end %>
          <div class="card-body">
            <h5 class="card-title"><%= link_to t_google(prodotto.nome_prodotto), prodotto_path(prodotto), class: 'text-decoration-none' %></h5>
            <p class="card-text"><strong><%= t('comune.prezzo') =%>:</strong> <%= number_to_currency(prodotto.prezzo, unit: "€") %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% else %>
  <p class="card-text"><%= t('negozio.no_prod') =%></p>
<% end %>

        </div>
      </div>

      <div class="d-flex justify-content-end">
        <%= link_to t('negozio.edit'), edit_negozio_path(@negozio), class: 'btn btn-warning me-2' %>
        <%= button_to t('negozio.delete'), negozio_path(@negozio), method: :delete, data: { turbo: false, confirm: 'Sei sicuro di voler eliminare il profilo?' }, class: 'btn btn-danger' %>
      </div>
    </div>
  </div>
</div>

emarket/app/views/negozios/statistiche.html.erb
<%= stylesheet_link_tag 'app', media: 'all' %>

<p id="notice"><%= t_google(notice) %></p>
<div class="statistiche-container">
  <h2><%= t('stat_n.gen') =%></h2>
  <ul>
    <li><%= t('stat_n.tot') =%>: <%= @totale_vendite %></li>
    <li><%= t('stat_n.guad_mese') =%>: €<%= number_with_precision(@guadagni_ultimo_mese, precision: 2) %></li>
    <li><%= t('stat_n.guad_anno') =%>: €<%= number_with_precision(@guadagni_ultimo_anno, precision: 2) %></li>
    <li><%= t('stat_n.prod_vendita') =%>: <%= @prodotti_in_vendita %></li>
    <li><%= t('stat_n.prezzo_medio') =%>: €<%= number_with_precision(@media_prezzo, precision: 2) %></li>
  </ul>

  <h2><%= t('stat_n.prod') =%></h2>
  <table class="table">
    <thead>
      <tr>
        <th><%= t('stat_n.nome') =%></th>
        <th><%= t('stat_n.vend') =%></th>
        <th><%= t('stat_n.disp') =%></th>
        <th><%= t('stat_n.vend_mese') =%></th>
        <th><%= t('stat_n.vend_anno') =%></th>
      </tr>
    </thead>
    <tbody>
      <% @statistiche_per_prodotto.each do |stat| %>
        <tr>
          <td><%= t_google(stat[:prodotto].nome_prodotto) %></td>
          <td><%= stat[:venduti] %></td>
          <td><%= stat[:disponibili] %></td>
          <td><%= stat[:venduti_ultimo_mese] %></td>
          <td><%= stat[:venduti_ultimo_anno] %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

emarket/app/views/negozios/visualizza.html.erb
<p><%= t_google(notice) %></p>
<!DOCTYPE html>
<html>
<head>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'app', media: 'all' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <main class="negozio-page container">
    
    <% if @negozio.present? %>
      <section class="negozio-info card">
        <h1 class="negozio-nome"><%= t_google(@negozio.nome_negozio) %></h1>
        <p class="negozio-descrizione"><%= t_google(@negozio.descrizione) %></p>

        <% if @negozio.immagine.attached? %>
          <div class="negozio-img-wrapper">
            <%= image_tag @negozio.immagine.variant(resize_to_limit: [300, 300]), class: "negozio-img" %>
          </div>
        <% end %>

        <p><strong><%= t('negozio.indirizzo') =%>:</strong> <%= @negozio.indirizzo %></p>
        <p><strong><%= t('comune.telefono') =%></strong> <%= @negozio.telefono %></p>
        <p><strong>Followers:</strong> <%= @negozio.followers.count %></p>

        <% if current_user.is_a?(Acquirente) %>
          <div class="negozio-actions">
            <%= button_to t('gest.segnala') , segnala_form_negozio_path(@negozio), method: :get, class: "btn btn-danger" %>

            <% if current_user.follows.exists?(negozio: @negozio) %>
              <%= button_to t('negozio.non_seguire'), negozio_unfollow_path(@negozio), method: :delete, class: "btn btn-warning" %>
            <% else %>
              <%= button_to t('negozio.segui'), negozio_follow_path(@negozio), method: :post, class: "btn btn-primary" %>
            <% end %>

            <%= button_to t('negozio.scrivici'), start_chat_rooms_path(destinatario_id: @negozio.id, destinatario_type: "Negozio"), method: :post, class: "btn btn-secondary" %>
          </div>
        <% end %>
      </section>
    <% else %>
      <p><%= t('negozio.no_neg') =%></p>
    <% end %>

    <section class="proprietario card">
      <% if @negozio&.acquirente.present? %>
        <p><strong><%= t('negozio.proprietario') =%>:</strong> <%= t_google(@negozio.acquirente.nome_utente) %></p>
      <% else %>
        <p><%= t('negozio.no_prop') =%></p>
      <% end %>
    </section>

    <section class="prodotti card">
      <h2><%= t('negozio.prodotti') =%></h2>
      <% if @negozio&.prodottos.present? %>
        <div class="prodotti-grid">
        <% @negozio.prodottos.each do |prodotto| %>
          <%= link_to prodotto_path(prodotto), class: "card prodotto-card text-decoration-none text-dark" do %>
            <p class="prodotto-nome"><%= t_google(prodotto.nome_prodotto) %></p>
            <p class="prodotto-descrizione"><%= t_google(prodotto.descrizione) %></p>
          <% end %>
        <% end %>
        
        </div>
      <% else %>
        <p><%= t('negozio.no_prodotti') =%></p>
      <% end %>
    </section>
  </main>
</body>
</html>